In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
data = pd.read_csv('./data/실버타운목록.csv', 
                  
                  low_memory=False)

In [17]:
data

    Unnamed: 0            시설명                       주소
0            1    서울시니어스 서울타워                중구 다산로 72
1            2    서울시니어스 강서타워             강서구 공항대로 315
2            3          정동상림원             중구 정동길 21-31
3            4          후성누리움               강동구 명일로135
4            5        시니어캐슬클라         은평구 은평로 21길 34-5
5            6    서울시니어스 가양타워          강서구 화곡로 68길 102
6            7         노블레스타워               성북구 종암로 90
7            8         하이원빌리지          용산구 한강대로40가길 24
8            9        더클래식500               광진구 능도로 90
9           10       상암카이져팰리스          마포구 월드컵북로47길 37
10          11    서울시니어스 강남타워            강남구 자곡로 100-2
11          12        더시그넘하우스           강남구 자곡로 204-25
12          13           유당마을     수원시 장안구 수일로 191번길 26
13          14       미리내 실버타운    안성시 양성면 미리내성지로 386-27
14          15        삼성노블카운티        용인시 기흥구 덕영대로 1751
15          16    서울시니어스 분당타워     성남시 분당구 구미로 173번길 47
16          17        수동시니어타운      남양주시 수동면 비룡로 801-88
17          18          정원속궁전          성남시 분당구 불정로 112
18          19          청심빌리지      가평군 설악면 미사리로 191-16
19          20        성남시 아리움           성남시 중원구 광명로 46
20          21         더 헤리티지        성남시 분당구 대왕판교로 155
21          22        블루밍더클래식             하남시 하남대로 770
22          23        광교 아르데코      수원시 영통구 광교로 42번길 80
23          24     안성크리스챤휴빌리지    안성시 양성면 미리내성지로 274-31
24          25        광교 두산위브        수원시 영통구 광교 중앙로 55
25          26           엔젤아크        성남시 중원구 시민로 6번길20
26          27       스프링카운티자이           기흥구 동백죽전대로 333
27          28         에버그린센터  남양주시 수동면 비룡로 1782번길 160
28          29       생명의빛 홈타운        가평군 설악면 봉미산안길 335
29          30          마리스텔라           서구 심곡로100번길 31
30          31        사이언스빌리지             유성구 대덕대로 522
31          32        밀마루복지마을          세종시 보듬1로 16, 1층
32          33          공주원로원           공주시 연수원길 47-30
33          34     동해약천온천실버타운       동해시 석두골길 145 (망상동)
34          35       김제노인전용주택            김제시 하동1길 79-1
35          36      내장산 실버아파트              정읍시금붕1길 190
36          37        옥성골든카운티      전주시 완산구 중인1길 136-20
37          38    서울시니어스 고창타워          고창군 고창읍석정2로 140
38          39  월명성모의집 노인복지주택       김천시 남면 주천로 1448-16
39          40         일붕실버랜드       의령군 궁류면 청정로1180-42
40          41         흰돌실버타운         수영구 연수로 260번길 53

In [18]:
data.주소.value_counts()

주소
중구 다산로 72                  1
하남시 하남대로 770               1
안성시 양성면 미리내성지로 274-31      1
수원시 영통구 광교 중앙로 55          1
성남시 중원구 시민로 6번길20          1
기흥구 동백죽전대로 333             1
남양주시 수동면 비룡로 1782번길 160    1
가평군 설악면 봉미산안길 335          1
서구 심곡로100번길 31             1
유성구 대덕대로 522               1
세종시 보듬1로 16, 1층            1
공주시 연수원길 47-30             1
동해시 석두골길 145 (망상동)         1
김제시 하동1길 79-1              1
정읍시금붕1길 190                1
전주시 완산구 중인1길 136-20        1
고창군 고창읍석정2로 140            1
김천시 남면 주천로 1448-16         1
의령군 궁류면 청정로1180-42         1
수원시 영통구 광교로 42번길 80        1
성남시 분당구 대왕판교로 155          1
강서구 공항대로 315               1
성남시 중원구 광명로 46             1
중구 정동길 21-31               1
강동구 명일로135                 1
은평구 은평로 21길 34-5           1
강서구 화곡로 68길 102            1
성북구 종암로 90                 1
용산구 한강대로40가길 24            1
광진구 능도로 90                 1
마포구 월드컵북로47길 37            1
강남구 자곡로 100-2              1
강남구 자곡로 204-25             1
수원시 장안구 수일로 191번길 26       1
안성시 양성면 미리내성지로 386-27      1
용인시 기흥구 덕영대로 1751          1
성남시 분당구 구미로 173번길 47       1
남양주시 수동면 비룡로 801-88        1
성남시 분당구 불정로 112            1
가평군 설악면 미사리로 191-16        1
수영구 연수로 260번길 53           1
Name: count, dtype: int64

In [19]:
addr = data.주소.str.slice(start=0, stop=4)
addr
addr.value_counts()

data.주소 = addr

In [20]:
data

    Unnamed: 0            시설명    주소
0            1    서울시니어스 서울타워  중구 다
1            2    서울시니어스 강서타워  강서구
2            3          정동상림원  중구 정
3            4          후성누리움  강동구
4            5        시니어캐슬클라  은평구
5            6    서울시니어스 가양타워  강서구
6            7         노블레스타워  성북구
7            8         하이원빌리지  용산구
8            9        더클래식500  광진구
9           10       상암카이져팰리스  마포구
10          11    서울시니어스 강남타워  강남구
11          12        더시그넘하우스  강남구
12          13           유당마을  수원시
13          14       미리내 실버타운  안성시
14          15        삼성노블카운티  용인시
15          16    서울시니어스 분당타워  성남시
16          17        수동시니어타운  남양주시
17          18          정원속궁전  성남시
18          19          청심빌리지  가평군
19          20        성남시 아리움  성남시
20          21         더 헤리티지  성남시
21          22        블루밍더클래식  하남시
22          23        광교 아르데코  수원시
23          24     안성크리스챤휴빌리지  안성시
24          25        광교 두산위브  수원시
25          26           엔젤아크  성남시
26          27       스프링카운티자이  기흥구
27          28         에버그린센터  남양주시
28          29       생명의빛 홈타운  가평군
29          30          마리스텔라  서구 심
30          31        사이언스빌리지  유성구
31          32        밀마루복지마을  세종시
32          33          공주원로원  공주시
33          34     동해약천온천실버타운  동해시
34          35       김제노인전용주택  김제시
35          36      내장산 실버아파트  정읍시금
36          37        옥성골든카운티  전주시
37          38    서울시니어스 고창타워  고창군
38          39  월명성모의집 노인복지주택  김천시
39          40         일붕실버랜드  의령군
40          41         흰돌실버타운  수영구

In [23]:
data.주소

0     중구 다
1     강서구
2     중구 정
3     강동구
4     은평구
5     강서구
6     성북구
7     용산구
8     광진구
9     마포구
10    강남구
11    강남구
12    수원시
13    안성시
14    용인시
15    성남시
16    남양주시
17    성남시
18    가평군
19    성남시
20    성남시
21    하남시
22    수원시
23    안성시
24    수원시
25    성남시
26    기흥구
27    남양주시
28    가평군
29    서구 심
30    유성구
31    세종시
32    공주시
33    동해시
34    김제시
35    정읍시금
36    전주시
37    고창군
38    김천시
39    의령군
40    수영구
Name: 주소, dtype: object

In [28]:
data_addr = pd.DataFrame([['서울시', '경기도', '인천광역시', '대전광역시', '세종특별자치시', '충청도', '강원도', '전라도', '경상도', '부산광역시'], [12, 17, 1, 1, 1, 1, 1, 4, 2, 1]])

In [31]:
data_addr = data_addr.T

In [34]:
data_addr.rename(columns={0:'지역', 1: '실버타운 수'}, inplace=True)

In [35]:
data_addr.set_index('지역', inplace=True)

In [36]:
data_addr

        실버타운 수
지역
서울시         12
경기도         17
인천광역시        1
대전광역시        1
세종특별자치시      1
충청도          1
강원도          1
전라도          4
경상도          2
부산광역시        1

In [37]:
data_addr.to_csv('./data/전국_실버타운_분포_data.csv')

In [41]:
data_g = data.iloc[12:29]

In [44]:
data_g.주소.value_counts()

주소
성남시     5
수원시     3
안성시     2
남양주시    2
가평군     2
용인시     1
하남시     1
기흥구     1
Name: count, dtype: int64

In [45]:
data_g = pd.DataFrame(data_g.주소.value_counts())

In [48]:
data_g.rename(columns={'count':'실버타운 수'}, inplace=True)

In [50]:
data_g.to_csv('./data/경기도_실버타운_분포_data.csv')